### ISSUE TITLE
Allow app.py to be bound to a specific address

### ISSUE THREAD

**Issue by pnorman** [emacsen/changemonger#13]
Currently app.py binds to 127.0.0.1:5000. For those of us who browse from a different IP than we run python programs, this does not work.

Command line options to specify the port and IP would be useful and eliminate the need to edit app.py.

**Comment by emacsen** [comment]
Ultimately I'd like changemonger to be an installable library with lots of people writing applications around it, and I consider app.py (the web app) to be an example. Still, if it's something that you'd find useful, I can certainly do that.

**Comment by emacsen** [comment]
Done.
